#######################################################################
# Ping Identity DevOps Chart
########################################################################
apiVersion: v2
name: ping-devops
########################################################################
# 0.11.7 - Refer to http://helm.pingidentity.com/release-notes/currentRelease
########################################################################
version: 0.11.7
description: Ping Identity helm charts - May 1, 2025
type: application
home: https://helm.pingidentity.com/
icon: https://helm.pingidentity.com/img/logos/ping.png
appVersion: "2504"
