#######################################################################
# Ping Identity DevOps Chart
########################################################################
apiVersion: v2
name: ping-devops
########################################################################
# 0.9.5 - Refer to http://helm.pingidentity.com/release-notes/currentRelease
########################################################################
version: 0.9.5
description: Ping Identity helm charts - 09/01/22
type: application
home: https://helm.pingidentity.com/
icon: https://helm.pingidentity.com/img/logos/ping.png
appVersion: "2208"
