#######################################################################
# Ping Identity DevOps Chart
########################################################################
apiVersion: v2
name: ping-devops
########################################################################
# 0.10.6 - Refer to http://helm.pingidentity.com/release-notes/currentRelease
########################################################################
version: 0.10.6
description: Ping Identity helm charts - 07/02/2024
type: application
home: https://helm.pingidentity.com/
icon: https://helm.pingidentity.com/img/logos/ping.png
appVersion: "2406"
