#######################################################################
# Ping Identity DevOps Chart
########################################################################
apiVersion: v2
name: ping-devops
########################################################################
# 0.4.0 - Refer to http://helm.pingidentity.com/release-notes/#release-040
# 0.4.1 - Refer to http://helm.pingidentity.com/release-notes/#release-041
# 0.4.2 - Refer to http://helm.pingidentity.com/release-notes/#release-042
# 0.4.3 - Refer to http://helm.pingidentity.com/release-notes/#release-043
# 0.4.4 - Refer to http://helm.pingidentity.com/release-notes/#release-044
# 0.4.5 - Refer to http://helm.pingidentity.com/release-notes/#release-045
# 0.4.6 - Refer to http://helm.pingidentity.com/release-notes/#release-046
# 0.4.7 - Refer to http://helm.pingidentity.com/release-notes/#release-047
########################################################################
version: 0.4.8
description: All Ping Identity product images with integration
type: application
home: https://devops.pingidentity.com/
appVersion: "2101"
