{{- include "pinglib.env-vars" (list . "pingfederate-admin") -}}


{{- define "pingfederate-admin.env-vars" -}}
data:
  OPERATIONAL_MODE: CLUSTERED_CONSOLE
{{ include "pinglib.env-vars.pingfederate" . | nindent 2 }}
{{- end -}}
