{{- include "pinglib.deployment" (list . "pingfederate-engine") -}}


{{- define "pingfederate-engine.deployment" -}}
{{- $top := index . 0 -}}
{{- $v := index . 1 -}}
spec:
  template:
    metadata:
      labels:
        clusterIdentifier: {{ include "pinglib.fullimagename" . }}
    spec:
      initContainers:
      - name: init
        image: {{ $v.externalImages.curl }}
        command: ['sh', '-c', 'until curl --connect-timeout 1 --silent -k https://{{ include "pinglib.fullname" . | replace "-engine" "-admin" }}:{{ $v.envs.PF_ADMIN_PORT }}/pingfederate/app ; do echo waiting for https://{{ include "pinglib.fullname" . | replace "-engine" "-admin" }}:{{ $v.envs.PF_ADMIN_PORT }}/pingfederate/app ; sleep 2 ; done']

{{- end -}}