{{- include "pinglib.env-vars" (list . "pingfederate-engine") -}}


{{- define "pingfederate-engine.env-vars" -}}
data:
  OPERATIONAL_MODE: CLUSTERED_ENGINE
{{ include "pinglib.env-vars.pingfederate" . | nindent 2 }}
{{- end -}}
