################################################
# The purpose of the integration test below is
# to verify replication between two
# instances of PingDirectory
intel.pd-repl.liberica:
  stage: test.integration
  script:
    - ci_scripts/run_helm_integration.sh --integration-test pd-replicated --helm-chart charts/ping-devops/
  retry: 2
  variables:
    KUBERNETES_CPU_REQUEST: 1900m
    KUBERNETES_CPU_LIMIT: 1900m
    KUBERNETES_MEMORY_REQUEST: 3920000000
    KUBERNETES_MEMORY_LIMIT: 3920000000
  except:
    variables:
      - $CI_COMMIT_TAG
      - $SKIP_TESTS == "true"
      - $RELEASE == "true"

################################################
# The purpose of the integration test below is
# to verify replication between two
# instances of PingDirectory
arm.pd-repl.liberica:
  stage: test.integration
  image: $RUNNER_IMAGE_AARCH64
  tags:
    - platform=aarch64
  script:
    - ci_scripts/run_helm_integration.sh --integration-test pd-replicated --helm-chart charts/ping-devops/
  retry: 2
  variables:
    KUBERNETES_CPU_REQUEST: 1900m
    KUBERNETES_CPU_LIMIT: 1900m
    KUBERNETES_MEMORY_REQUEST: 3920000000
    KUBERNETES_MEMORY_LIMIT: 5880000000
  except:
    variables:
      - $CI_COMMIT_TAG
      - $SKIP_TESTS == "true"
      - $RELEASE == "true"

################################################
# The purpose of the integration test below is
# to verify PingAccess, PingFederate and PingDirectory
# integrate together into an end to end test
intel.pa-pf-pd.liberica:
  stage: test.integration
  script:
    - ci_scripts/run_helm_integration.sh --integration-test pa-pf-pd --helm-chart charts/ping-devops/
  retry: 2
  variables:
    KUBERNETES_CPU_REQUEST: 2850m
    KUBERNETES_CPU_LIMIT: 2850m
    KUBERNETES_MEMORY_REQUEST: 3920000000
    KUBERNETES_MEMORY_LIMIT: 3920000000
  except:
    variables:
      - $CI_COMMIT_TAG
      - $SKIP_TESTS == "true"
      - $RELEASE == "true"

################################################
# The purpose of the integration test below is
# to verify PingAccess, PingFederate and PingDirectory
# integrate together into an end to end test
arm.pa-pf-pd.liberica:
  stage: test.integration
  image: $RUNNER_IMAGE_AARCH64
  tags:
    - platform=aarch64
  script:
    - ci_scripts/run_helm_integration.sh --integration-test pa-pf-pd --helm-chart charts/ping-devops/
  retry: 2
  variables:
    KUBERNETES_CPU_REQUEST: 1900m
    KUBERNETES_CPU_LIMIT: 1900m
    KUBERNETES_MEMORY_REQUEST: 3920000000
    KUBERNETES_MEMORY_LIMIT: 5880000000
  except:
    variables:
      - $CI_COMMIT_TAG
      - $SKIP_TESTS == "true"
      - $RELEASE == "true"

################################################
# The purpose of the integration test below is
# to verify PingDataSync and PingDirectory
# integrate together into an end to end test
intel.pds-pd.liberica:
  stage: test.integration
  script:
    - ci_scripts/run_helm_integration.sh --integration-test pds-pd --helm-chart charts/ping-devops/
  retry: 2
  variables:
    KUBERNETES_CPU_REQUEST: 1900m
    KUBERNETES_CPU_LIMIT: 1900m
    KUBERNETES_MEMORY_REQUEST: 3920000000
    KUBERNETES_MEMORY_LIMIT: 3920000000
  except:
    variables:
      - $CI_COMMIT_TAG
      - $SKIP_TESTS == "true"
      - $RELEASE == "true"

################################################
# The purpose of the integration test below is
# to verify PingDataSync and PingDirectory
# integrate together into an end to end test
arm.pds-pd.liberica:
  stage: test.integration
  image: $RUNNER_IMAGE_AARCH64
  tags:
    - platform=aarch64
  script:
    - ci_scripts/run_helm_integration.sh --integration-test pds-pd --helm-chart charts/ping-devops/
  retry: 2
  variables:
    KUBERNETES_CPU_REQUEST: 1900m
    KUBERNETES_CPU_LIMIT: 1900m
    KUBERNETES_MEMORY_REQUEST: 3920000000
    KUBERNETES_MEMORY_LIMIT: 5880000000
  except:
    variables:
      - $CI_COMMIT_TAG
      - $SKIP_TESTS == "true"
      - $RELEASE == "true"

################################################
# The purpose of the integration test below is
# to verify PingDirectoryProxy and PingDirectory
# integrate together into an end to end test
intel.pdp-pd.liberica:
  stage: test.integration
  script:
    - ci_scripts/run_helm_integration.sh --integration-test pdp-pd --helm-chart charts/ping-devops/
  retry: 2
  variables:
    KUBERNETES_CPU_REQUEST: 1900m
    KUBERNETES_CPU_LIMIT: 1900m
    KUBERNETES_MEMORY_REQUEST: 3920000000
    KUBERNETES_MEMORY_LIMIT: 5880000000
  except:
    variables:
      - $CI_COMMIT_TAG
      - $SKIP_TESTS == "true"
      - $RELEASE == "true"

################################################
# The purpose of the integration test below is
# to verify PingDirectoryProxy and PingDirectory
# integrate together into an end to end test
arm.pdp-pd.liberica:
  stage: test.integration
  image: $RUNNER_IMAGE_AARCH64
  tags:
    - platform=aarch64
  script:
    - ci_scripts/run_helm_integration.sh --integration-test pdp-pd --helm-chart charts/ping-devops/
  retry: 2
  variables:
    KUBERNETES_CPU_REQUEST: 1900m
    KUBERNETES_CPU_LIMIT: 1900m
    KUBERNETES_MEMORY_REQUEST: 3920000000
    KUBERNETES_MEMORY_LIMIT: 3920000000
  except:
    variables:
      - $CI_COMMIT_TAG
      - $SKIP_TESTS == "true"
      - $RELEASE == "true"

################################################
# The purpose of the integration test below is
# to verify PingAuthorize and PingDirectory
# integrate together into an end to end test
intel.paz-pd.liberica:
  stage: test.integration
  script:
    - ci_scripts/run_helm_integration.sh --integration-test paz-pd --helm-chart charts/ping-devops/
  retry: 2
  variables:
    KUBERNETES_CPU_REQUEST: 1900m
    KUBERNETES_CPU_LIMIT: 1900m
    KUBERNETES_MEMORY_REQUEST: 3920000000
    KUBERNETES_MEMORY_LIMIT: 3920000000
  except:
    variables:
      - $CI_COMMIT_TAG
      - $SKIP_TESTS == "true"
      - $RELEASE == "true"

################################################
# The purpose of the integration test below is
# to verify PingAuthorize and PingDirectory
# integrate together into an end to end test
arm.paz-pd.liberica:
  stage: test.integration
  image: $RUNNER_IMAGE_AARCH64
  tags:
    - platform=aarch64
  script:
    - ci_scripts/run_helm_integration.sh --integration-test paz-pd --helm-chart charts/ping-devops/
  retry: 2
  variables:
    KUBERNETES_CPU_REQUEST: 1900m
    KUBERNETES_CPU_LIMIT: 1900m
    KUBERNETES_MEMORY_REQUEST: 3920000000
    KUBERNETES_MEMORY_LIMIT: 5880000000
  except:
    variables:
      - $CI_COMMIT_TAG
      - $SKIP_TESTS == "true"
      - $RELEASE == "true"

################################################
# The purpose of the integration test below is
# to verify PingAccess, PingFederate and PingDirectory
# integrate together into an end to end test
# in FIPS mode
intel.pa-pf-pd-fips.liberica:
  stage: test.integration
  script:
    - ci_scripts/run_helm_integration.sh --integration-test pa-pf-pd-fips --helm-chart charts/ping-devops/
  retry: 2
  variables:
    KUBERNETES_CPU_REQUEST: 2850m
    KUBERNETES_CPU_LIMIT: 2850m
    KUBERNETES_MEMORY_REQUEST: 1960000000
    KUBERNETES_MEMORY_LIMIT: 1960000000
  except:
    variables:
      - $CI_COMMIT_TAG
      - $SKIP_TESTS == "true"
      - $RELEASE == "true"